### PR TITLE
updating static/admin for django 1.9.6

### PR DESCRIPTION
**Pull request by medullaskyline**
Just assigning @s-paquette because she's done some updating of libraries. This is just adding new image, css, and js files to static/admin for our django admin site.

### CODE REVIEW

**Comment by s-paquette** [comment]
Woops! Sorry, missed this email. Doing it now. :)

**Comment by s-paquette** [comment]
...so, now that I'm looking at this, I realize...I don't know what it is. Is static/admin a part of Django?

**Comment by phyllers** [comment]
We had to copy in all the static django admin pages to be able to use the admin site. I remember this was definitely the case back when we were in appengine, do we know if we still need to do this? Could be clean this up and still be able to use the django admin pages?

**Comment by s-paquette** [comment]
Unfortunately I don't really have any familiarity with the Django admin side of things so I don't know. Relating to the actual PR, if this was just copied from somewhere else in 1.9.6 it should go over fine, but as you said maybe we don't need to do that now?

**Comment by medullaskyline** [comment]
We had to copy all the admin files into static/admin in order to be able to use the admin console, yes. I suppose that has to do with how we configure our static files directory? you two probably know more about that than I do.

So if "clean this up" means "delete the static/admin directory", then no.

We can still use the django admin, of course -- it just looks ugly with missing things like svg files. To avoid that, every time we upgrade a version of django we will have to copy over the upgraded static/admin files.

Unless there's some other way I don't know about yet.

**Comment by s-paquette** [comment]
If there's no way to tell app engine/our container to alias to the lib directory where these files come from, then copying them would be our only option. But typically what's done is the location within Django is mapped so the web server knows where to find those files. Is there a way to do that with how we're serving the application now?

**Comment by phyllers** [comment]
I honestly don't know. Let's merge this in for now and create a new issue to investigate the django admin static files.

**Comment by medullaskyline** [comment]
Just to clarify -- yes, we have to manually copy over the static/admin files because of the way we have django running on app engine (or rather the mangaged vm) through the lib directory. If someone figures out a better way to alias the lib directory as suzanne commented, great.

This is how we've been using the django admin all along. I'm not creating anything new here. The changes are just upgrading img files to svg, tweaking some of the css, etc. So this pull request isn't creating anything new that wasn't there before. In case that wasn't clear.

**Comment by s-paquette** [comment]
Sounds good--and yeah we can look at other options separately.

**Comment by medullaskyline** [comment]
@s-paquette According to [this](https://django-staticfiles.readthedocs.io/en/latest/) we just need to have `ADMIN_MEDIA_PREFIX = STATIC_URL + "admin/"` in settings.py in order for collectstatic to work for the django admin static files.

**Comment by phyllers** [comment]
Does that still work even if we don't have the admin app in our django project?

**Pull request merged**
