### PR TITLE
Bug 1394

### PR DESCRIPTION
**Pull request by s-paquette**
- Truncate names in the flyouts to 30 characters and show ... to prevent fyouts from going off screen
- This is for Sprint 6

### CODE REVIEW

**Comment by phyllers** [comment]
Ugh, I just merged it, but I realized this probably should have been done using css overflow. Maybe lets make a new enhancement for that.

**Comment by s-paquette** [comment]
I was thinking of that, but can overflow be set to put the ... at the end? Otherwise it'll just be cut off mid-word

**Comment by phyllers** [comment]
yup, it's text-overflow: ellipses 

https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

**Comment by s-paquette** [comment]
Ah ha, yeah that should be easy enough to drop in. I'll change it next sprint. (Net effect: same visual.)

**Pull request merged**
