### PR TITLE
bug #1394

### PR DESCRIPTION
**Pull request by s-paquette**
-> Enabled scrolling on header menu flyouts, set max height to 500px
-> Skinned flyout scrollbars to be more visible (will only work in webkit browsers)
-> This will also fix the same bug for any other flyout on the menu bar

### CODE REVIEW

**Comment by phyllers** [comment]
I think scrollbars OS specific (like checkboxes). I'd rather not impose our own styles on them. Can we remove that skinning?

**Comment by s-paquette** [comment]
By OS specific do you mean you can't see them? Because AFAIK for webkit it will show them across OSes and for any Webkit browser (Chrome, Safari, Opera). The setting to show them or not is definitely browser specific, but that will happen regardless of whether or not we skin them, since it's an OS-level setting.

The problem is they're incredibly difficult to see without the skinning. If you think that's okay I'm fine to remove it, but I suspect this will fail contrast requirements for section 508.

**Comment by phyllers** [comment]
I haven't used a windows machine in a while, So i could be wrong about it being OS specific. (I was trying to recall from memory)

I don't know if the default style for the scrollbar should not trigger the 508 compliance. Have you tested that? I'm just thinking that if we add the styles to these panels, then we will need to add it to everywhere else we're using scroll panels and I prefer keeping them the default.

**Comment by s-paquette** [comment]
In looking at 508 compliance, it turns out the OSX setting to only show the scrollbar when mousing over a scrollable element (as opposed to any time an element is scrollable) is already out of compliance, so the contrast is kind of a non-issue anyways. I'll strip that out and push it shortly.

**Comment by s-paquette** [comment]
This one should be sorted out now and okay to merge.

**Pull request merged**
